CAMERA:
  IR:
    DEVICE: "/dev/video0"
  RGB_FRONT:
    FPS: 30
    RES: [1280, 720]
    SLEEP: 0.033
    DEVICE: "/dev/video2"

TARGET_RES: [960, 544]
MODEL: ./model/8n_640_v2/best_full_integer_quant.tflite
LABEL: ./model/labels.txt
DELEGATE: ""

INPUT:
  RGB:
    MODE: live
    VIDEO_PATH: ""
    LOOP: true
    FRAME_INTERVAL_MS: null
    COLOR: [0, 255, 0]
    DEVICE: "/dev/video2"
  IR:
    MODE: live
    VIDEO_PATH: ""
    LOOP: true
    FRAME_INTERVAL_MS: null
    DEVICE: "/dev/video0"

STATE:
  FIRE:
    CONFIDENCE: 0.2

SERVER:
  IP: '127.0.0.1'
  PORT: 9999
  COMP_RATIO: 70

DISPLAY:
  ENABLED: true
  WINDOW_NAME: "Vision AI Display"

CAPTURE:
  OUTPUT_DIR: "./capture_session_pc"
